### ISSUE TITLE
clicking overlay too soon breaks functionality

### ISSUE THREAD

**Issue by milholen** [buckwilson/Lightbox_me#17]
I found this problem on accident so I'm sure a user will stumble onto the issue eventually.

 I'm opening an overlay via a text link. If the overlay is clicked during the fade-in, the overlay itself will disappear, but the modal content that was positioned within the overlay remains visible. Clicking the "close" box in the overlay closes only the "close" box and leaves the rest of the modal content visible.

This is an internal beta project so I can't post a link, but I'll make a quick demo if needed. Just wanted to see if anyone else has noticed this. I can reproduce the issue on the Lightbox Me demo page, but the overlay has to be clicked at just the right moment.

**Comment by buckwilson** [comment]
Good catch, I'll revisit some of the logic to make sure this case can't be hit.

**Comment by milholen** [comment]
Just added the latest version of lightbox.me to a new project, seems like the issue was fixed. Thanks.

**Comment by thisgeek** [comment]
With the lastest verion (186abc8) I am able to trigger the `closeLightbox` function before the animation completes, e.g. if I double click on the element that triggers the lightbox plugin. Afterward, the modal element will appear, but the close event will have been unbound, leaving the user to have no way to escape the modal (without refreshing the page).

**Comment by seanyao** [comment]
this defect still exist, not fixed yet, and the other defect has been raised.
